

INVOICE_ID = 'invoice_id'
DEFAULT_INVOICE_ID = 'Invoice id'
INVOICE_DATETIME = 'invoice_datetime'
DEFAULT_INVOICE_DATETIME = 'Invoice date'
INVOICE = 'invoice'
DEFAULT_INVOICE = 'Invoice'
DUE_DATE = 'due_datetime'
DEFAULT_DUE_DATE = 'Invoice due date'
NAME = 'name'
DEFAULT_NAME = 'Name'
STREET = 'street'
DEFAULT_STREET = 'Street'
CITY = 'city'
DEFAULT_CITY = 'City'
STATE = 'state'
DEFAULT_STATE = 'State'
COUNTRY = 'country'
DEFAULT_COUNTRY = 'Country'
POST_CODE = 'post_code'
DEFAULT_POST_CODE = 'Post code'
VAT_TAX_NUMBER = 'vat_tax_number'
DEFAULT_VAT_TAX_NUMBER = 'Vat/Tax number'
MERCHANT = 'service_provider'
DEFAULT_MERCHANT = 'Service Provider'
EMAIL = 'email'
DEFAULT_EMAIL = 'Email'
CLIENT_ID = 'client_id'
DEFAULT_CLIENT_ID = 'Client id'
CLIENT = 'client'
DEFAULT_CLIENT = 'Client'
DETAIL = 'detail'
DEFAULT_DETAIL = 'Detail'
NAME = 'name'
DEFAULT_NAME = 'Name'
DESCRIPTION = 'description'
DEFAULT_DESCRIPTION = 'Description'
UNITS = 'units'
DEFAULT_UNITS = 'Units'
UNIT_PRICE = 'unit_price'
DEFAULT_UNIT_PRICE = 'Unit Price'
AMOUNT = 'amount'
DEFAULT_AMOUNT = 'Amount'
SUBTOTAL = 'subtotal'
DEFAULT_SUBTOTAL = 'Subtotal'
TAX = 'tax'
DEFAULT_TAX = 'Vat/Tax'
TOTAL = 'total'
DEFAULT_TOTAL = 'Total'
TRANSACTION_ID = 'transaction_id'
DEFAULT_TRANSACTION_ID = 'Transaction id'
GATEWAY = 'gateway'
DEFAULT_GATEWAY = 'Gateway'
TRANSACTION_DATE = 'transaction_date'
DEFAULT_TRANSACTION_DATE = 'Transaction date'
TRANSACTION = 'transaction'
DEFAULT_TRANSACTION = 'Transaction'

PYINVOICE_CONSTANTS = {
    INVOICE_ID: DEFAULT_INVOICE_ID,
    INVOICE_DATETIME: DEFAULT_INVOICE_DATETIME,
    DUE_DATE: DEFAULT_DUE_DATE,
    NAME: DEFAULT_NAME,
    STREET: DEFAULT_STREET,
    CITY: DEFAULT_CITY,
    STATE: DEFAULT_STATE,
    COUNTRY: DEFAULT_COUNTRY,
    POST_CODE: DEFAULT_POST_CODE,
    VAT_TAX_NUMBER: DEFAULT_VAT_TAX_NUMBER,
    MERCHANT: DEFAULT_MERCHANT,
    EMAIL: DEFAULT_EMAIL,
    CLIENT_ID: DEFAULT_CLIENT_ID,
    CLIENT: DEFAULT_CLIENT,
    DETAIL: DEFAULT_DETAIL,
    NAME: DEFAULT_NAME,
    DESCRIPTION: DEFAULT_DESCRIPTION,
    UNITS: DEFAULT_UNITS,
    UNIT_PRICE: DEFAULT_UNIT_PRICE,
    AMOUNT: DEFAULT_AMOUNT,
    SUBTOTAL: DEFAULT_SUBTOTAL,
    TAX: DEFAULT_TAX,
    TOTAL: DEFAULT_TOTAL, 
    TRANSACTION_ID: DEFAULT_TRANSACTION_ID,
    GATEWAY: DEFAULT_GATEWAY,
    TRANSACTION_DATE: DEFAULT_TRANSACTION_DATE,
    TRANSACTION: DEFAULT_TRANSACTION,
}
